const predefinedMessages = [
  "¡Gracias! Acabo de recibir mi producto gratis, el sitio es totalmente confiable.",
  "Hoy me llegó mi regalo gratuito, muchísimas gracias por esta oportunidad.",
  "Introduje mi número de teléfono, recibí una llamada del soporte y al poco tiempo me llegó el producto. ¡Gracias!",
  "Muchas gracias, recibí mi recompensa gratis sin ningún problema.",
  "¡Increíble! El equipo de soporte me llamó para confirmar mis datos y mi regalo llegó hoy.",
  "Gracias por el regalo gratuito, llegó en perfectas condiciones.",
  "No lo creía al principio, pero recibí el producto gratis. ¡Gracias!",
  "Me llamaron del soporte después de poner mi número y mi recompensa llegó rápido. ¡Gracias!",
  "Producto gratis recibido, estoy muy agradecido con el sitio.",
  "¡Mil gracias! Mi premio llegó completamente gratis.",
  "Acabo de recibir el paquete, muchas gracias por la recompensa gratuita.",
  "El soporte me llamó y confirmó mi información. El regalo llegó hoy. ¡Gracias!",
  "Muy contento, recibí mi producto gratis tal como prometieron.",
  "Gracias por enviarme el regalo sin costo alguno.",
  "Después de ingresar mi número, recibí una llamada y luego mi premio. Muchas gracias.",
  "Todo funcionó perfecto, mi recompensa gratuita llegó hoy.",
  "Gracias por el servicio, mi regalo llegó rápidamente.",
  "Recibí mi obsequio gratis. ¡Muy agradecido!",
  "Me sorprendió lo rápido que llegó el producto. ¡Gracias!",
  "El soporte me llamó para confirmar y mi regalo llegó al poco tiempo. ¡Gracias!",
  "Gracias por esta oportunidad, el producto gratis llegó sin problemas.",
  "Muy agradecido, recibí mi recompensa hoy.",
  "No tuve que pagar nada y aun así recibí mi regalo. ¡Gracias!",
  "Excelente servicio, mi producto llegó gratis y a tiempo.",
  "Después de ingresar mi número, recibí una llamada y luego el paquete. ¡Gracias!",
  "Muchas gracias, mi recompensa llegó sin costo.",
  "Producto recibido gratuitamente, excelente servicio.",
  "Gracias por el regalo, llegó mucho antes de lo que esperaba.",
  "El soporte verificó mis datos por teléfono y enviaron mi recompensa. ¡Gracias!",
  "Estoy muy feliz, mi producto gratis llegó hoy.",
  "Gracias, todo el proceso fue muy fácil y rápido.",
  "Recibí mi regalo después de la llamada del equipo de soporte. ¡Gracias!",
  "Mi producto gratuito finalmente llegó. Muchas gracias.",
  "El servicio es increíble, recibí mi obsequio gratis.",
  "Me llamaron para confirmar y luego llegó mi producto. ¡Gracias!",
  "Gracias por la recompensa gratuita, estoy muy satisfecho.",
  "Mi regalo llegó hoy sin pagar nada. ¡Gracias!",
  "Gracias al sitio, recibí mi producto de forma gratuita.",
  "El soporte llamó rápidamente y mi regalo llegó poco después. ¡Gracias!",
  "Estoy muy contento, la recompensa gratis llegó perfecta.",
  "Muchas gracias, el producto gratuito llegó sin inconvenientes.",
  "Recibí mi regalo gratis después de una llamada rápida del soporte. ¡Gracias!",
  "Muy satisfecho con el servicio, gracias por el regalo.",
  "El producto llegó gratis y en buen estado. ¡Gracias!",
  "Gracias por este regalo, llegó exactamente como prometieron.",
  "Después de poner mi número, me llamaron y enviaron mi recompensa. ¡Gracias!",
  "Muy agradecido, mi regalo gratuito llegó hoy.",
  "El sitio realmente funciona, recibí mi producto gratis. ¡Gracias!",
  "Todo salió perfecto, gracias por el obsequio.",
  "Introduje mi número y soporte me llamó. Recibí mi recompensa gratis. ¡Gracias!",
  "Gracias, estoy muy feliz con mi producto gratuito.",
  "Recibí mi regalo gratis sin ningún problema. ¡Gracias!",
  "El servicio es excelente, mi recompensa llegó gratis.",
  "Me llamó el soporte y al poco tiempo llegó mi producto. ¡Gracias!",
  "Gracias por el obsequio, llegó en muy buenas condiciones.",
  "Mi regalo gratuito finalmente llegó. ¡Gracias!",
  "Muy feliz con este sitio, recibí mi recompensa gratis.",
  "Después de la llamada del soporte, mi premio llegó rápido. ¡Gracias!",
  "Gracias por cumplir, recibí mi producto sin pagar nada.",
  "Mi recompensa llegó gratis y muy rápido. ¡Gracias!",
  "Excelente experiencia, gracias por el regalo.",
  "Me llamaron para confirmar mis datos y mi producto llegó hoy. ¡Gracias!",
  "Gracias, mi obsequio gratuito ya está aquí.",
  "No esperaba que fuera real, pero sí recibí mi regalo. ¡Gracias!",
  "Producto gratis recibido correctamente. ¡Muchas gracias!",
  "Gracias, todo el proceso fue sencillo y recibí mi recompensa.",
  "Soporte me llamó para verificar y el regalo llegó después. ¡Gracias!",
  "Estoy muy agradecido, mi producto llegó gratis.",
  "Gracias por enviarme mi premio gratis, llegó perfecto.",
  "Recibí una llamada de soporte y luego llegó mi producto. ¡Muchas gracias!",
  "Producto recibido sin pagar nada, muchas gracias.",
  "Gracias por el regalo gratuito, estoy muy contento.",
  "Mi recompensa llegó hoy y no tuve que pagar nada. ¡Gracias!",
  "El soporte me llamó y confirmó mi envío. Gracias por el regalo.",
  "Muy agradecido, recibí mi producto gratis sin problemas.",
  "Gracias por la recompensa gratuita, llegó tal como esperaba.",
  "Servicio excelente, mi obsequio llegó gratis. ¡Gracias!",
  "Recibí una llamada de confirmación y después el regalo. ¡Gracias!",
  "Estoy muy feliz, gracias por el producto gratuito.",
  "Gracias, mi recompensa llegó sin costo alguno.",
  "El sitio funciona, recibí mi regalo gratis. ¡Muchas gracias!",
  "Después de ingresar mi teléfono, me llamaron y enviaron mi producto. ¡Gracias!",
  "Obsequio recibido gratuitamente, muy agradecido.",
  "Gracias por el regalo, llegó muy rápido.",
  "Mi producto gratis llegó hoy, excelente servicio.",
  "Gracias, estoy sorprendido de lo rápido que llegó el regalo.",
  "El soporte fue muy amable en la llamada, y luego llegó mi recompensa. ¡Gracias!",
  "Muy satisfecho, gracias por mi producto gratuito.",
  "Regalo recibido gratis, todo perfecto. ¡Gracias!",
  "Muchísimas gracias, el paquete llegó sin costo.",
  "Me confirmaron por teléfono y luego enviaron mi regalo. ¡Gracias!",
  "Gracias, estoy muy contento con mi recompensa gratuita.",
  "Mi obsequio llegó gratis y en buen estado. ¡Gracias!",
  "El producto llegó perfecto y gratis. ¡Mil gracias!",
  "Gracias por cumplir con la recompensa gratuita.",
  "Me llamaron del soporte y luego llegó mi premio. ¡Gracias!",
  "Recibí mi regalo gratis. Muchas gracias.",
  "Gracias por este obsequio, llegó rápidamente.",
  "La llamada de soporte fue rápida y mi producto llegó pronto. ¡Gracias!",
  "Muy agradecido por el regalo gratuito.",
  "Gracias por enviar mi recompensa gratis, excelente servicio.",
  "El producto gratuito llegó hoy. Muchas gracias.",
  "Me llamaron para confirmar y luego enviaron mi obsequio. ¡Gracias!",
  "Gracias, estoy muy feliz con mi regalo gratis.",
  "Mi recompensa llegó gratis sin ningún inconveniente. ¡Gracias!",
  "Excelente servicio, gracias por el producto gratuito.",
  "Después de introducir mi número, me llamaron y enviaron mi recompensa. ¡Gracias!",
  "Gracias por el obsequio, llegó en perfectas condiciones.",
  "Regalo gratuito recibido hoy, muy agradecido.",
  "Gracias por la recompensa, llegó más rápido de lo esperado.",
  "Después de la llamada del soporte, la entrega fue inmediata. ¡Gracias!",
  "Muy agradecido, mi obsequio llegó sin problemas.",
  "Producto gratis recibido, excelente atención. ¡Gracias!",
  "Gracias, mi recompensa ya llegó y está perfecta.",
  "Me contactaron por teléfono y mi regalo llegó después. ¡Gracias!",
  "Muchas gracias, recibí mi premio gratis hoy.",
  "El servicio fue increíble, gracias por el regalo.",
  "Mi producto gratuito llegó rápido. ¡Gracias!",
  "Gracias por enviarme este obsequio sin costo.",
  "Me llamaron del soporte y luego llegó mi recompensa. ¡Gracias!",
  "Muy contento con el regalo gratuito, muchas gracias.",
  "Gracias por el producto gratis, llegó mejor de lo esperado.",
  "El soporte verificó todo por teléfono y enviaron mi regalo. ¡Gracias!",
  "Recibí mi obsequio gratis sin ningún problema. ¡Gracias!",
  "Muy agradecido, la recompensa llegó perfecta.",
  "El producto llegó gratis hoy, muchas gracias.",
  "Gracias por cumplir, mi premio llegó sin pagar nada.",
  "Todo salió excelente, gracias por el regalo gratuito.",
  "Después de introducir mi número, soporte me llamó y luego recibí el producto. ¡Gracias!",
  "Muchas gracias por mi obsequio gratuito, estoy muy feliz.",
  "Regalo recibido gratis y en perfecto estado. ¡Gracias!",
  "Gracias por el producto gratuito, llegó justo a tiempo.",
  "Soporte me llamó y mi recompensa llegó hoy. ¡Muchas gracias!",
  "Estoy muy agradecido con el sitio, recibí mi regalo gratis.",
  "Gracias, mi producto gratuito llegó sin inconvenientes.",
  "Todo funcionó muy bien, recibí mi obsequio. ¡Gracias!",
  "Mi recompensa llegó después de una llamada breve del soporte. ¡Gracias!",
  "Gracias por enviarme el regalo gratis.",
  "Estoy muy feliz con mi premio, llegó hoy. ¡Gracias!",
  "Recibí mi producto gratis y todo salió perfecto. ¡Gracias!",
  "Gracias, mi recompensa gratuita llegó muy rápido.",
  "Después de la llamada del soporte, mi obsequio llegó enseguida. ¡Gracias!",
  "Muy agradecido por el regalo gratuito.",
  "Gracias por este increíble obsequio, llegó sin pagar nada.",
  "Mi premio llegó gratis y sin retrasos. ¡Gracias!",
  "Me llamaron para confirmar y luego enviaron mi producto. ¡Gracias!",
  "Gracias por el regalo gratuito, estoy muy satisfecho.",
  "Todo perfecto, mi recompensa llegó gratis. ¡Gracias!",
  "Muy feliz, gracias por enviarme mi obsequio sin costo.",
  "Después de poner mi número, recibí una llamada y luego mi producto. ¡Gracias!",
  "Muchas gracias, mi regalo gratuito llegó hoy.",
  "Me encanta mi recompensa, gracias por enviarla gratis.",
  "Gracias por el producto gratis, llegó antes de lo esperado.",
  "El soporte fue amable en la llamada y mi regalo llegó después. ¡Gracias!"
];
