const predefinedMessages = [
  "Hey, has anyone completed the survey yet?",
  "I just finished it, waiting for my reward to arrive.",
  "Do we need to enter real info for the reward to come?",
  "Yes, I used my real info and my gift arrived a few hours later.",
  "Just clicked the sponsor link, filled survey, fingers crossed!",
  "Completed the survey yesterday, my reward just arrived. Works perfectly!",
  "Can someone explain which fields are required in the survey?",
  "Fill all required fields honestly, optional fields don’t affect reward much.",
  "Finished survey, reward came a few hours later, very impressed!",
  "How long does it usually take for the reward to be delivered?",
  "For me, it took around 3 hours, everything was smooth.",
  "Thanks for the tip! I filled mine and will wait patiently.",
  "Finally got my reward! Survey completed yesterday, site is legit!",
  "Do we need to sign up with the same email as account?",
  "Yes, use your main email, my prize arrived safely that way.",
  "Completed survey, reward delivered after some hours, excellent service!",
  "Should we fill optional questions or just required ones?",
  "I skipped optional, reward still came a few hours later.",
  "Just received my gift, survey done hours ago, amazing!",
  "Reward took some time, but everything worked fine. Very satisfied.",
  "Do they check if info is fake?",
  "Yes, make sure info is real, reward comes correctly afterward.",
  "Finished survey, reward arrived safely, highly recommended!",
  "Can someone tell me if clicking sponsor link twice is okay?",
  "Better do it once, filled honestly, reward arrived after waiting.",
  "Big thanks! Prize came after a couple of hours, very happy!",
  "Completed survey, gift sent safely after some hours, site legit!",
  "How detailed should we answer the survey questions?",
  "Just honestly, reward arrives after a while, trust the process.",
  "Filled survey and finally received my reward, very impressed!",
  "Do we need to submit immediately or can we take time?",
  "You can take a bit, but reward only comes after submission.",
  "Just got my gift! Survey completed earlier today, smooth process!",
  "Reward arrived a few hours later, everything worked perfectly!",
  "Completed survey, prize delivered after some time, very happy!",
  "Anyone else waiting for their reward after filling survey?",
  "Yes, mine came after a couple of hours, site is reliable!",
  "Should we use our real email or a temporary one?",
  "Use real email, reward comes safely only then.",
  "Completed survey, received gift after waiting, excellent experience!",
  "Big thanks! Filled everything and reward came a few hours later!",
  "How long after survey does reward appear usually?",
  "Mine took 2-3 hours, but arrived correctly without issues.",
  "Reward finally arrived! Filled survey properly, highly satisfied.",
  "Do optional questions affect reward?",
  "Not really, required fields are enough, but answer honestly.",
  "Just received my gift, survey done yesterday, amazing site!",
  "Completed all steps, reward delivered after waiting a bit, very happy!",
  "Should we enter accurate info for each field?",
  "Absolutely, accurate info ensures reward delivery.",
  "Finished survey, reward sent after some time, site is legit!",
  "Prize arrived safely after a few hours, everything smooth.",
  "Big thanks! Survey done and reward came correctly!",
  "Anyone else notice delay in reward delivery?",
  "Yes, normal to wait a few hours, it always comes.",
  "Completed survey, reward arrived later, highly recommended!",
  "Do we need to confirm email after survey?",
  "Yes, confirm your email, reward will follow shortly.",
  "Filled survey, gift received a few hours later, very happy!",
  "Thanks for guidance, prize arrived after waiting, site works perfectly!",
  "Should we answer optional survey questions or not?",
  "Optional is optional, required fields matter most for reward.",
  "Completed survey and finally received my gift safely, excellent!",
  "Reward came a few hours later, very satisfied with site.",
  "Can someone tell me if survey needs to be fully complete?",
  "Yes, all required fields must be filled honestly, reward comes later.",
  "Just received my prize, survey completed yesterday, site legit!",
  "Big thanks, reward delivered safely after a few hours, amazing!",
  "Do we need to use sponsor link exactly?",
  "Yes, use official sponsor, fill survey, reward comes after waiting.",
  "Finished survey, reward came safely after some hours, very happy!",
  "Prize finally arrived, all steps completed, excellent service!",
  "Anyone got their reward immediately?",
  "No, reward always comes after some hours, patience is key.",
  "Completed survey, reward delivered correctly after waiting, site works!",
  "Do optional fields affect timing?",
  "Not much, only required fields are critical for reward.",
  "Just received my gift! Filled survey honestly, arrived safely.",
  "Big thanks! Rewar
